import type { Metadata } from 'next';
import { Merriweather_Sans, Open_Sans } from 'next/font/google';
import './globals.css';

const merriWeather = Merriweather_Sans({
  variable: '--font-merriWeather-sans',
  subsets: ['latin'],
});
const openSans = Open_Sans({
  variable: '--font-open_sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${openSans.variable} antialiased`}
    >
      <body className={`${merriWeather.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
